// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonopolyWebApp.Database;

#nullable disable

namespace MonopolyWebApp.Migrations
{
    [DbContext(typeof(MonopolyDBContext))]
    [Migration("20240310222553_Rents")]
    partial class Rents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonopolyWebApp.Data.Rent", b =>
                {
                    b.Property<int>("RentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentID"));

                    b.Property<int>("RentBase")
                        .HasColumnType("int");

                    b.Property<int>("RentFour")
                        .HasColumnType("int");

                    b.Property<int>("RentHotel")
                        .HasColumnType("int");

                    b.Property<int>("RentOne")
                        .HasColumnType("int");

                    b.Property<int>("RentThree")
                        .HasColumnType("int");

                    b.Property<int>("RentTwo")
                        .HasColumnType("int");

                    b.HasKey("RentID");

                    b.ToTable("Rents");

                    b.HasData(
                        new
                        {
                            RentID = 1,
                            RentBase = 2,
                            RentFour = 160,
                            RentHotel = 250,
                            RentOne = 10,
                            RentThree = 90,
                            RentTwo = 30
                        },
                        new
                        {
                            RentID = 2,
                            RentBase = 4,
                            RentFour = 320,
                            RentHotel = 450,
                            RentOne = 20,
                            RentThree = 180,
                            RentTwo = 60
                        },
                        new
                        {
                            RentID = 3,
                            RentBase = 25,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 50,
                            RentThree = 200,
                            RentTwo = 100
                        },
                        new
                        {
                            RentID = 4,
                            RentBase = 6,
                            RentFour = 400,
                            RentHotel = 550,
                            RentOne = 30,
                            RentThree = 270,
                            RentTwo = 90
                        },
                        new
                        {
                            RentID = 5,
                            RentBase = 6,
                            RentFour = 400,
                            RentHotel = 550,
                            RentOne = 30,
                            RentThree = 270,
                            RentTwo = 90
                        },
                        new
                        {
                            RentID = 6,
                            RentBase = 8,
                            RentFour = 450,
                            RentHotel = 600,
                            RentOne = 40,
                            RentThree = 300,
                            RentTwo = 100
                        },
                        new
                        {
                            RentID = 7,
                            RentBase = 10,
                            RentFour = 625,
                            RentHotel = 750,
                            RentOne = 50,
                            RentThree = 450,
                            RentTwo = 150
                        },
                        new
                        {
                            RentID = 8,
                            RentBase = 0,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 0,
                            RentThree = 0,
                            RentTwo = 0
                        },
                        new
                        {
                            RentID = 9,
                            RentBase = 10,
                            RentFour = 625,
                            RentHotel = 750,
                            RentOne = 50,
                            RentThree = 450,
                            RentTwo = 150
                        },
                        new
                        {
                            RentID = 10,
                            RentBase = 12,
                            RentFour = 700,
                            RentHotel = 900,
                            RentOne = 60,
                            RentThree = 500,
                            RentTwo = 180
                        },
                        new
                        {
                            RentID = 11,
                            RentBase = 25,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 50,
                            RentThree = 200,
                            RentTwo = 100
                        },
                        new
                        {
                            RentID = 12,
                            RentBase = 14,
                            RentFour = 750,
                            RentHotel = 950,
                            RentOne = 70,
                            RentThree = 550,
                            RentTwo = 200
                        },
                        new
                        {
                            RentID = 13,
                            RentBase = 14,
                            RentFour = 750,
                            RentHotel = 950,
                            RentOne = 70,
                            RentThree = 550,
                            RentTwo = 200
                        },
                        new
                        {
                            RentID = 14,
                            RentBase = 16,
                            RentFour = 800,
                            RentHotel = 1000,
                            RentOne = 80,
                            RentThree = 600,
                            RentTwo = 220
                        },
                        new
                        {
                            RentID = 15,
                            RentBase = 18,
                            RentFour = 875,
                            RentHotel = 1050,
                            RentOne = 90,
                            RentThree = 700,
                            RentTwo = 250
                        },
                        new
                        {
                            RentID = 16,
                            RentBase = 18,
                            RentFour = 875,
                            RentHotel = 1050,
                            RentOne = 90,
                            RentThree = 700,
                            RentTwo = 250
                        },
                        new
                        {
                            RentID = 17,
                            RentBase = 20,
                            RentFour = 925,
                            RentHotel = 1100,
                            RentOne = 100,
                            RentThree = 750,
                            RentTwo = 300
                        },
                        new
                        {
                            RentID = 18,
                            RentBase = 25,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 50,
                            RentThree = 200,
                            RentTwo = 100
                        },
                        new
                        {
                            RentID = 19,
                            RentBase = 22,
                            RentFour = 975,
                            RentHotel = 1150,
                            RentOne = 110,
                            RentThree = 800,
                            RentTwo = 330
                        },
                        new
                        {
                            RentID = 20,
                            RentBase = 22,
                            RentFour = 975,
                            RentHotel = 1150,
                            RentOne = 110,
                            RentThree = 800,
                            RentTwo = 330
                        },
                        new
                        {
                            RentID = 21,
                            RentBase = 0,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 0,
                            RentThree = 0,
                            RentTwo = 0
                        },
                        new
                        {
                            RentID = 22,
                            RentBase = 24,
                            RentFour = 1025,
                            RentHotel = 1200,
                            RentOne = 120,
                            RentThree = 850,
                            RentTwo = 360
                        },
                        new
                        {
                            RentID = 23,
                            RentBase = 26,
                            RentFour = 1100,
                            RentHotel = 1275,
                            RentOne = 130,
                            RentThree = 900,
                            RentTwo = 390
                        },
                        new
                        {
                            RentID = 24,
                            RentBase = 26,
                            RentFour = 1100,
                            RentHotel = 1275,
                            RentOne = 130,
                            RentThree = 900,
                            RentTwo = 390
                        },
                        new
                        {
                            RentID = 25,
                            RentBase = 28,
                            RentFour = 1200,
                            RentHotel = 1400,
                            RentOne = 150,
                            RentThree = 1000,
                            RentTwo = 450
                        },
                        new
                        {
                            RentID = 26,
                            RentBase = 25,
                            RentFour = 0,
                            RentHotel = 0,
                            RentOne = 50,
                            RentThree = 200,
                            RentTwo = 100
                        },
                        new
                        {
                            RentID = 27,
                            RentBase = 35,
                            RentFour = 1300,
                            RentHotel = 1500,
                            RentOne = 175,
                            RentThree = 1100,
                            RentTwo = 500
                        },
                        new
                        {
                            RentID = 28,
                            RentBase = 50,
                            RentFour = 1700,
                            RentHotel = 2000,
                            RentOne = 200,
                            RentThree = 1400,
                            RentTwo = 600
                        });
                });

            modelBuilder.Entity("MonopolyWebApp.Data.Space", b =>
                {
                    b.Property<int>("SpaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceID"));

                    b.Property<int>("BuildingAmount")
                        .HasColumnType("int");

                    b.Property<bool>("HasProp")
                        .HasColumnType("bit");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("SpaceID");

                    b.HasIndex("PropertyId");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("MonopolyWebApp.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChanceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            Action = "advanceGo",
                            ChanceId = 0,
                            Description = "Advance to Go (collect 200$)",
                            Price = 0
                        },
                        new
                        {
                            CardId = 2,
                            Action = "advanceProp17",
                            ChanceId = 0,
                            Description = "Advance to Trafalgar Square(prop17). If you pass Go, collect $200",
                            Price = 0
                        },
                        new
                        {
                            CardId = 3,
                            Action = "advanceProp7",
                            ChanceId = 0,
                            Description = "Advance to PallMall(prop7) If you pass Go, collect $200",
                            Price = 0
                        },
                        new
                        {
                            CardId = 4,
                            Action = "advanceUtility",
                            ChanceId = 0,
                            Description = "Advance to nearest Utility",
                            Price = 0
                        },
                        new
                        {
                            CardId = 5,
                            Action = "advanceRailroad",
                            ChanceId = 0,
                            Description = "Advance to nearest Railroad",
                            Price = 0
                        },
                        new
                        {
                            CardId = 6,
                            Action = "advanceRailroad",
                            ChanceId = 0,
                            Description = "Advance to nearest Railroad",
                            Price = 0
                        },
                        new
                        {
                            CardId = 7,
                            Action = "bankDividend",
                            ChanceId = 0,
                            Description = "Bank pays you dividend of $50",
                            Price = 0
                        },
                        new
                        {
                            CardId = 8,
                            Action = "jailFree",
                            ChanceId = 0,
                            Description = "Get Out of Jail Free!",
                            Price = 0
                        },
                        new
                        {
                            CardId = 9,
                            Action = "goBack3",
                            ChanceId = 0,
                            Description = "Go back 3 spaces",
                            Price = 0
                        },
                        new
                        {
                            CardId = 10,
                            Action = "jail",
                            ChanceId = 0,
                            Description = "Go directly to Jail. Do not pass Go, do not collect $200",
                            Price = 0
                        },
                        new
                        {
                            CardId = 11,
                            Action = "generalRepairs",
                            ChanceId = 0,
                            Description = "Make general repairs on all your property. For each house, pay $25. For each hotel, pay $100.",
                            Price = 0
                        },
                        new
                        {
                            CardId = 12,
                            Action = "poorTax",
                            ChanceId = 0,
                            Description = "Pay Poor Tax of $15",
                            Price = 0
                        },
                        new
                        {
                            CardId = 13,
                            Action = "advanceProp3",
                            ChanceId = 0,
                            Description = "Advance to King Cross St(prop3). If you pass Go, collect $200",
                            Price = 0
                        },
                        new
                        {
                            CardId = 14,
                            Action = "advanceProp28",
                            ChanceId = 0,
                            Description = "Advance to Mayfair(prop28). If you pass Go, collect $200",
                            Price = 0
                        },
                        new
                        {
                            CardId = 15,
                            Action = "chairman",
                            ChanceId = 0,
                            Description = "You have been elected Chairman of the Board. Pay each player $50",
                            Price = 0
                        },
                        new
                        {
                            CardId = 16,
                            Action = "matures",
                            ChanceId = 0,
                            Description = "Your building and loan matures. Collect $150",
                            Price = 0
                        });
                });

            modelBuilder.Entity("MonopolyWebApp.Models.Property", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<int>("BuildingCost")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMortagaged")
                        .HasColumnType("bit");

                    b.Property<int>("MortageValue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("RentID")
                        .HasColumnType("int");

                    b.HasKey("PropertyID");

                    b.HasIndex("RentID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("MonopolyWebApp.Data.Space", b =>
                {
                    b.HasOne("MonopolyWebApp.Models.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("MonopolyWebApp.Models.Property", b =>
                {
                    b.HasOne("MonopolyWebApp.Data.Rent", "Rent")
                        .WithMany()
                        .HasForeignKey("RentID");

                    b.Navigation("Rent");
                });
#pragma warning restore 612, 618
        }
    }
}
